### ISSUE TITLE
On top of tabbar

### ISSUE THREAD

**Issue by anonrig** [danielsaidi/BottomSheet#12]
Hi @danielsaidi 

Thank you for this fantastic library. I just had a question and wanted to ask here for future reference (and for SEO). How can I make sure that the bottomSheet is shown on top of the Tabbar?

**Comment by danielsaidi** [comment]
Hi @anonrig - thanks, big cred to Majid for the original concept :)

You can try out how this would behave, by wrapping the demo's `ContentView` content in a `TabView`:

```swift
var body: some View {
    TabView {
        NavigationView {
            ...
        }
    }
}
```

As you'll notice, the bottom bar will then overlap the tab view, which may not be the best solution design-wise.

If you'd like to have a bottom sheet applied to a root tab view regardless, you'd just have to replace the demo's `ContentView` approach with having its own state, with injecting state to binding values instead, so that the views can control the outermost sheet by changing the binding values.
